version: '2'
services:
  rowbot:
    build:
      context: .
    ports:
      - "80:5000"
    volumes:
      - /var/pipecontrol:/server/pipecontrol/databases

  dev:
    build:
      context: .
    ports:
      - "80:5000"
    volumes:
      - $PWD:/server/pipecontrol
