version: '2'

services:
  pipecontrol:
    build: .
    ports:
      - "80:5000"
    environment:
      - PIPELINE_CONFIG=production

  development:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/server/pipecontrol
      - $HOME/code/pipecontrol/tmp/:/tmp
    environment:
      - PIPELINE_CONFIG=development
