version: '2'
services:
  pipecontrol:
    build:
      context: .
    ports:
      - "80:5000"

  dev:
    build:
      context: .
    ports:
      - "80:5000"
    volumes:
      - $PWD:/server/pipecontrol
