version: '3'

services:
  pipecontrol:
    build: .
    ports:
      - "80:5000"
    volumes:
      - /tmp:/tmp
    environment:
      - PIPELINE_CONFIG=production
    env_file: .env

  development:
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/server/pipecontrol
      - $HOME/Documents/pipecontrol/tmp/:/tmp
    environment:
      - PIPELINE_CONFIG=development
    env_file: .env
